### ISSUE TITLE
additional packages needed to create iso image

### ISSUE THREAD

**Issue by blomstertj** [rockstor/rockstor-installer#79]
Hey all

So I built the installer with 15.2 Leap in a vagrant box but had some errors building the image due to missing commands.

The command
 `kiwi-ng --profile=Leap15.2.x86_64 --type oem system build --description ./ --target-dir /home/kiwi-images/`
Failed a couple times due to missing commands.  I got the build to work after installing these packages:
qemu-tools
gptfdisk
e2fsprogs
squashfs
xorriso

**Comment by phillxnet** [comment]
@blomstertj Thanks for the feedback. 

It looks like the vagrant box image you used simply did not have these pre-installed. Many such images are trimmed right down. Good to know. We have had some reports over time of variations in Leap images with regard to this. As there is no harm in requesting the install of packages that are already installed (on other Leap images) we should add these to our following line:
```
sudo zypper install python3-kiwi btrfsprogs gfxboot
```
and ideally to the Leap 15.3 equivalent if the packages are named the same (which I think they will be).

The "btrfsprogs gfxboot" entries there were similarly added due to some JeOS modelled images that were found to have no btrfs pre-installed.

I'll get to adding these shortly.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
@blomstertj Thanks again for the report. Much appreciated.

I've now, in the linked pull request, added these package dependencies to the non boxbuild methods.

"Update package dependencies for kiwi-ng non boxbuild methods #79" #80
